# Page settings

baseURL = "https://villeve.github.io/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"





    
[params]
    author = "Villeve"
    description = "My Resume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Ville Vehniä"
        tagline = "Software Developer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Tampere, Finland"

        #[[params.contact.list]]
        #icon = "fas fa-phone-square"
        #url = "tel:#"
        #text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "ville.vehnia@gmail.com"
        #[[params.contact.list]]
        #icon = "fas fa-globe"
        #url = "#"
        #text = "www.yourwebsite.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/TypeScript"
        [[params.skills.list.items]]
        details = "Node/Vue/React"
        [[params.skills.list.items]]
        details = "Python/Django/Flask"
        [[params.skills.list.items]]
        details = "Java/PHP"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL/MongoDB"
        [[params.skills.list.items]]
        details = "Docker/Microservices"
        [[params.skills.list.items]]
        details = "Azure/Active Directory"
        [[params.skills.list.items]]
        details = "Keycloak/IAM"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Automation and Information Technology"
        university = "University of Vaasa"
        dates = "2018 - 2020"
        [[params.education.list]]
        degree = "BSc in Energy and Information Technology"
        university = "University of Vaasa"
        dates = "2015 - 2018"








    #[params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "Finnish"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Basketball"
        [[params.interests.list]]
        name = "Games, Movies & Books"
        [[params.interests.list]]
        name = "Programming"


    [params.summary]
        enable = true
        text = "Ville is an ambitious problem solver and a capable software developer. He has recently graduated from University of Vaasa (Automation and Information Technology) while working as a software developer at Insta Digital. Having a passion towards full-stack web development and cloud services guides his way on the path of becoming a software architect."


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Junior Software Developer"
        dates = "2019 - Present"
        company = "Insta Digital Oy"
        details = "Consultant role which mainly focuses on full-stack web development combined with some integration, deployment and maintenance work. Projects vary from modern applications with microservice architecture to more traditional monolithic applications."
        #[[params.experience.list.items]]
        #details = "Lorem ipsum dolor sit amet, consectetuer."
        #[[params.experience.list.items]]
        #details = "Aenean commodo ligula eget dolor."
        #[[params.experience.list.items]]
        #details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Summer Trainee"
        dates = "Summer (2018, 2019)"
        company = "Freeport Cobalt Oy"
        details = "Management of ICT infrastructure and information systems in Windows/Azure environment. Occasionally some Help Desk duties, management of mobile devices (AirWatch, Intune) and daily problem solving."


    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Multitude of Subjects"
        meta = "Open Source"
        tagline = "A multitude of my personal side projects can be found on my Github page (link on the footer). The projects include items I have completed as course work during my studies and other varying stuff done just for fun."


    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2020 · Implementing Azure Active Directory Integration with an Existing Cloud Service"
        [[params.information.list.items]]
        details = "2018 · SigFox: Overview of Technology, Services and Expendature"

        [[params.information.list]]
        title = "Interests"
        details = "Basketball, Metal music, Online games (MMORPGs and MOBAs), Movies & Books."


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/villeve"
        title = "Villeve"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/ville-vehniä-963965158"
        title = "Ville Vehniä"





